# SOPS configuration for encrypted secrets
# Single secrets file for both dev and prod

creation_rules:
  - path_regex: secrets\.yaml$
    age: age1m2w4k4rgnzdynx0s9xqvx7k66dfa4jv5q20hgxp6dcjjwz09mdlqqzgves
