# Auto-generated by Terraform - do not edit manually
# Run 'terraform apply' to update

all:
  children:
    seance:
      hosts:
        ${server_name}:
          ansible_host: ${server_ip}
          ansible_user: root
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
